language: python
python:
    - "3.5"
    - "3.6"

# Travis comes with an old pytest that does not work with pytest-flake8
# So upgrade that first.
before_install:
  - pip install --upgrade pytest

install:
  - pip install codacy-coverage

script: make test

after_success:
    - python-codacy-coverage -r coverage.xml
