# Run Continuous Integration on every push
# This version tests only Python, but on all supported versions of it.
name: python_compatibility
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Python tests on 3.5
      run: docker run -v "${GITHUB_WORKSPACE}:/home/muscle3_src" python:3.5 /bin/bash -c 'cp -r /home/muscle3_src /home/muscle3 && cd /home/muscle3 && pip install ymmsl==0.10.0 && make test_python_only'
